apiVersion: v1
kind: ConfigMap
 
metadata:
  name: prometheus-config-map
  namespace: default
 
data:
  prometheus.yml: |
    global:
      scrape_interval: 2s
      scrape_timeout: 2s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['http://fresherdreamjob.com/task/metrics']
        
