apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
 
metadata:
  name: monitor-cluster-role
 
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "endpoints"]
    verbs: ["get", "watch", "list"]
  - nonResourceURLs: ["http://fresherdreamjob.com/task/metrics"]
    verbs: ["get"]
