name: ReviewDog CI

on:
  pull_request:

jobs:
  reviewdog-github-check:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    name: reviewdog (github-check)
    runs-on: [self-hosted]
    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      HOME: "/home/runner"
      GOCACHE: "/home/runner/.cache/go-build"
      GOENV: "/home/runner/.config/go/env"
      GOMODCACHE: "/home/runner/go/pkg/mod"
      GOOS: "linux"
      GOPATH: "/home/runner/go"

    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ~1.16

      - name: Install golint
        run: go get -u golang.org/x/lint/golint

      - name: Run reviewdog action setup
        uses: reviewdog/action-setup@v1

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          reviewdog -diff='git diff master' -conf=.reviewdog.yml -reporter=github-pr-review -runners=golint,golangci -fail-on-error -level=info -tee
