name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v3
      - name: misspell
        uses: ./
        with:
          github_token: ${{ secrets.git_token }}
          locale: "US"
          pattern: "*.md"
